### ISSUE TITLE
Import multiple PBF files

### ISSUE THREAD

**Issue by olleg** [Overv/openstreetmap-tile-server#58] opened 2019-09-05 11:56 UTC
Is that possible? 

When I use tool like osmium to merge multiple PBF I get error during import. 

Best option would be that I could import many PBFs one after another.

**Comment by Istador** [comment] 2019-09-06 07:52
Duplicate of issues #20 and #50.

Without the command with that you are trying to merge and the error message, we can't know or replicate what's going wrong.

I never used `osmium` to merge, but only `osmconvert`. Examples can be found in issue #2.

Importing them one after another is also an option (with `--append` of `osm2pgsql`), but it takes orders of magnitude more time to import.

**Closed** 2019-09-06 09:18 UTC

**Comment by olleg** [comment] 2019-09-10 15:53
Hello!

Thanks for help. I don't know what was the problem, but indeed osmium merge don't work here and end up with faulty results. 

However, I tried osmconvert as suggested and got it working absolutely fine!
