### ISSUE TITLE
Update does not work | osmosis error

### ISSUE THREAD

**Issue by lakul** [Overv/openstreetmap-tile-server#134] opened 2020-05-15 11:20 UTC
On a newly installed Ubuntu 20.04 LTS, I executed the following commands:

> sudo docker run \
> -e UPDATES=enabled \
> -e THREADS=16 \
> -e "OSM2PGSQL_EXTRA_ARGS=-C 80000" \
> -v /var/tmp/sachsen-latest.osm.pbf:/var/tmp/data.osm.pbf \
> -v /var/tmp/sachsen.poly:/var/tmp/data.poly \
> -v openstreetmap-data:/var/lib/postgresql/12/main \
> -v openstreetmap-rendered-tiles:/var/lib/mod_tile \
> overv/openstreetmap-tile-server \
> import

and run

> sudo docker run \
> -p 80:80 \
> --restart=always \
> -e THREADS=16 \
> -e UPDATES=enabled \
> -e "OSM2PGSQL_EXTRA_ARGS=-C 80000" \
> -v openstreetmap-data:/var/lib/postgresql/12/main \
> --shm-size="192m" \
> -e ALLOW_CORS=enabled \
> -v openstreetmap-rendered-tiles:/var/lib/mod_tile \
> -d overv/openstreetmap-tile-server \
> run

Everything is flawless. The tile server is running fine. Unfortunately the updates do not work. I find the following error in the logs:
run.log
> [2020-05-15 11:04:01] 2398 start import from seq-nr 4019747, replag is 1 day(s) and 11 hour(s)
> [2020-05-15 11:04:01] 2398 downloading diff
> [2020-05-15 11:04:01] 2398 [error] Osmosis error
> [2020-05-15 11:04:01] 2398 resetting state`

osmosis.log
> May 15, 2020 11:14:02 AM org.openstreetmap.osmosis.core.Osmosis run
> INFO: Osmosis Version 0.46
> May 15, 2020 11:14:02 AM org.openstreetmap.osmosis.core.Osmosis run
> INFO: Preparing pipeline.
> May 15, 2020 11:14:02 AM org.openstreetmap.osmosis.core.Osmosis run
> INFO: Launching pipeline execution.
> May 15, 2020 11:14:02 AM org.openstreetmap.osmosis.core.Osmosis run
> INFO: Pipeline executing, waiting for completion.
> May 15, 2020 11:14:02 AM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
> SEVERE: Thread for task 1-read-replication-interval failed
> org.openstreetmap.osmosis.core.OsmosisRuntimeException: The replication state doesn't contain a timestamp property.
>         at org.openstreetmap.osmosis.replication.common.ReplicationState.loadProperty(ReplicationState.java:65)
>         at org.openstreetmap.osmosis.replication.common.ReplicationState.load(ReplicationState.java:78)
>         at org.openstreetmap.osmosis.replication.common.ReplicationState.<init>(ReplicationState.java:59)
>         at org.openstreetmap.osmosis.replication.common.ServerStateReader.getServerState(ServerStateReader.java:103)
>         at org.openstreetmap.osmosis.replication.common.ServerStateReader.getServerState(ServerStateReader.java:46)
>         at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.runImpl(BaseReplicationDownloader.java:257)
>         at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.run(BaseReplicationDownloader.java:350)
>         at java.base/java.lang.Thread.run(Thread.java:834)

> May 15, 2020 11:14:02 AM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
> org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
>         at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
>         at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
>         at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
>         at org.codehaus.classworlds.Launcher.main(Launcher.java:47)`

What could be the reason for that? Thanks a lot.

**Comment by lakul** [comment] 2020-05-15 11:33
During the import, I found this. Should there be something behind the = at osmosis_replication_timestamp?

> + '[' -n https://download.geofabrik.de/europe/luxembourg.poly ']'
> + echo 'INFO: Download PBF-POLY file: https://download.geofabrik.de/europe/luxembourg.poly'
> + wget -nv https://download.geofabrik.de/europe/luxembourg.poly -O /data.poly
2020-05-15 11:26:52 URL:https://download.geofabrik.de/europe/luxembourg.poly [7021/7021] -> "/data.poly" [1]
> + '[' enabled = enabled ']'
> + osmium fileinfo /data.osm.pbf
> + grep osmosis_replication_timestamp=
> + osmium fileinfo /data.osm.pbf
> + cut -b35-44
> ++ cat /var/lib/mod_tile/replication_timestamp.txt
> + REPLICATION_TIMESTAMP=2020-05-14

**Comment by Istador** [comment] 2020-05-15 14:02
> Everything is flawless. The tile server is running fine.

Does it serve correct tiles for Sachsen or for Luxembourg?

Because your volume mounts for the `import` seems to be wrong:

> -v /var/tmp/sachsen-latest.osm.pbf:/var/tmp/data.osm.pbf 
> -v /var/tmp/sachsen.poly:/var/tmp/data.poly 

It should have been:
```
-v /var/tmp/sachsen-latest.osm.pbf:/data.osm.pbf 
-v /var/tmp/sachsen.poly:/data.poly 
```

---

Reply via e-mail from lakul:
> During the import, I found this. Should there be something behind the = at osmosis_replication_timestamp?
> 
> > \+ '[' -n https://download.geofabrik.de/europe/luxembourg.poly ']'
> > \+ echo 'INFO: Download PBF-POLY file: https://download.geofabrik.de/europe/luxembourg.poly'
> > \+ wget -nv https://download.geofabrik.de/europe/luxembourg.poly -O /data.poly
2020-05-15 11:26:52 URL:https://download.geofabrik.de/europe/luxembourg.poly [7021/7021] -> "/data.poly" [1]
> > \+ '[' enabled = enabled ']'
> > \+ osmium fileinfo /data.osm.pbf
> > \+ grep osmosis_replication_timestamp=
> > \+ osmium fileinfo /data.osm.pbf
> > \+ cut -b35-44
> > \+\+ cat /var/lib/mod_tile/replication_timestamp.txt
> > \+ REPLICATION_TIMESTAMP=2020-05-14

No, that's correct. It just prints the commands that it executes, and the `grep 'osmosis_replication_timestamp='` is a sub command chained like this:
https://github.com/Overv/openstreetmap-tile-server/blob/2754592d1ceea1fb3148037b70b075ab1f7758db/run.sh#L63-L64

The important part to take away from it, is that `REPLICATION_TIMESTAMP=2020-05-14` contains a value I guess.

---

I think this issue is a duplicate of issue #129, because it has the same error message:
> org.openstreetmap.osmosis.core.OsmosisRuntimeException: The replication state doesn't contain a timestamp property. [...]

**Comment by lakul** [comment] 2020-05-15 14:53
I copied the wrong import code, sorry.
Oh, thank you very much! Yes, I had read that, but I couldn't believe that this was the reason for the mistake. Now it works.

**Closed** 2020-05-15 16:51 UTC
